# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	#config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
	#config.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "127.0.0.1"
	#config.vm.network "forwarded_port", guest: 35729, host: 35729, host_ip: "127.0.0.1"
	config.vm.network "forwarded_port", guest: 4200, host: 4200, host_ip: "127.0.0.1"
	#config.vm.network "private_network", ip: "192.168.33.10"
	#config.vm.network "public_network"
	config.vm.provider "virtualbox" do |vb|
	vb.memory = "1024"
end
config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update
	sudo apt-get install -y g++
	#curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
	curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
	sudo apt-get install -y nodejs	
	sudo npm install karma
	sudo npm install -g @angular/cli
	sudo apt-get install build-essential libssl-dev libffi-dev python-dev
	SHELL
end